# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ICWE2024 - Vanilla JS Tutorial
email: to.muench@muench-its.de
author: Tobias Münch
heading: "Design and Implementation of a Progressive Web Application from Scratch"
subheading: "Tobias Münch"
description: >- # this means to ignore newlines until "baseurl:"
  Vanilla JS - Design and Implementation of a Progressive Web Application from Scratch
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
future: true
github_username:  tomuench
copyright: "{currentYear} {author}"

banner:
  image: /assets/images/tutorial.webp
  opacity: 0.5

# Build settings
theme: jekyll-theme-yat
plugins:
  - jekyll-spaceship
  - jekyll-feed

translate_langs:
  - lang: en
    img: https://cdn.countryflags.com/thumbs/england/flag-400.png
    text: English
  - lang: de
    img: https://cdn.countryflags.com/thumbs/germany/flag-400.png
    text: German
  - lang: fr
    img: https://cdn.countryflags.com/thumbs/france/flag-400.png
    text: French
  - lang: es
    img: https://cdn.countryflags.com/thumbs/spain/flag-400.png
    text: Spain